# Generated by Django 2.1.7 on 2019-03-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190314_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='assist_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Accounts'),
        ),
    ]
