# Generated by Django 2.1.7 on 2019-03-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190315_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='Classifications',
        ),
        migrations.RenameModel(
            old_name='Tickets_Form',
            new_name='TicketForms',
        ),
        migrations.RenameModel(
            old_name='User_Type',
            new_name='UserTypes',
        ),
        migrations.AlterModelTable(
            name='classifications',
            table='classifications',
        ),
        migrations.AlterModelTable(
            name='usertypes',
            table='user_types',
        ),
    ]
