# Generated by Django 2.1.7 on 2019-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190318_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
