# Generated by Django 2.1.7 on 2019-03-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190318_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Classifications',
            new_name='Classification',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='TicketForms',
            new_name='TicketForm',
        ),
        migrations.RenameModel(
            old_name='UserTypes',
            new_name='UserType',
        ),
    ]
